// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz_backend.Data;

#nullable disable

namespace Quiz_backend.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230904220338_Pocetna_Migracija")]
    partial class Pocetna_Migracija
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Quiz_backend.Model.Player", b =>
                {
                    b.Property<int>("IgracId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Victories")
                        .HasColumnType("int");

                    b.HasKey("IgracId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Quiz_backend.Model.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Answer2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Answer3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Answer4")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Quiz_backend.Model.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PlayerId1")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId2")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("QuizId");

                    b.HasIndex("PlayerId1");

                    b.HasIndex("PlayerId2");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Quiz_backend.Model.Quiz", b =>
                {
                    b.HasOne("Quiz_backend.Model.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("PlayerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quiz_backend.Model.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("PlayerId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });
#pragma warning restore 612, 618
        }
    }
}
